/// Flutter icons Cad
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CadIcons
///      fonts:
///       - asset: fonts/CadIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class CadIcons {
  CadIcons._();

  static const _kFontFam = 'CadIcons';
  static const String? _kFontPkg = null;

  static const IconData eye = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeOff = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData addPlus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData combine = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hide = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonEdges = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polygonVerticies = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData snapToGrid = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uncombine = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData controlPointDuplicate = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData floppy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData connection = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cheese = IconData(0xe961, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docText = IconData(0xf0f6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docInv = IconData(0xf15b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData docTextInv = IconData(0xf15c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropbox = IconData(0xf16b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calculator = IconData(0xf1ec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xf466, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxes = IconData(0xf468, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData boxOpen = IconData(0xf49e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
